version: "3.7"

services:

  redis:
    image: redis
    container_name: tutorial_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: node_redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  server:
    container_name: node_redis
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
    ports:
     - 5000:5000
    volumes:
      - ./:/var/app
    depends_on:
      - redis