module.exports = {
  ...require("./calc-score-on-create-account"),
  ...require("./calc-score-on-create-post"),
  ...require("./calc-score-on-upvote-post"),
  ...require("./calc-score-on-cancel-upvote-post"),
  ...require("./calc-score-on-downvote-post"),
  ...require("./calc-score-on-cancel-downvote-post"),
  ...require("./calc-score-on-block-user-post"),
  ...require("./calc-score-on-comment-post"),
  ...require("./calc-score-on-view-post"),
  ...require("./calc-score-on-follow-user"),
  ...require("./calc-score-on-unfollow-user"),
  ...require("./update-final-user-score-on-daily-process"),
  ...require("./update-user-score-on-daily-process-phase1"),
  ...require("./update-post-score-on-daily-process"),
  ...require("./trigger-daily-process"),
  ...require("./calc-score-on-sync-user-score"),
};
